services:
  - type: web
    name: mountebank
    env: docker
    dockerfilePath: ./Dockerfile # You'll need to create a Dockerfile
    dockerContext: .
    healthCheckPath: /imposters
    envVars:
      - key: MB_BIND_ADDR
        value: 0.0.0.0
    ports:
      - port: 2525
        protocol: tcp
      - port: 8080
        protocol: tcp
      - port: 3000
        protocol: tcp
    disk:
      mountPath: /imposters
      name: mountebank-imposters
