services:
  - type: web
    name: mountebank
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /imposters
    envVars:
      - key: MB_BIND_ADDR
        value: 0.0.0.0
      - key: PORT # Añade esta variable de entorno
        value: 10000
    ports:
      - port: 10000 # Puerto principal
        protocol: http
